"""Add index to candidate name

Revision ID: bc3ca9e2ba43
Revises: c32abcbafbd5
Create Date: 2020-06-11 08:51:54.668722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3ca9e2ba43'
down_revision = 'c32abcbafbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidate_name'), 'candidate', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_name'), table_name='candidate')
    # ### end Alembic commands ###
