"""Add drawer_ip

Revision ID: c32abcbafbd5
Revises: 1a199298087e
Create Date: 2020-06-11 05:44:41.487848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32abcbafbd5'
down_revision = '1a199298087e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('drawer_ip', sa.String(128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'drawer_ip')
    # ### end Alembic commands ###
